export class TypesModals {
    public static PROFILE: string = "profile"
    public static SHOP_COINS: string = "shopCoins"
    public static SHOP_GEMS: string = "shopGems"
    public static SHOP_OBJECT: string = "shopObject"
    public static EXPERIENCE: string = "experience"
    public static POWER: string = "power"
    public static CHARACTERS: string = "сharacters"
    public static CHARACTER_INFO: string = "characterInfo"
    public static CHARACTER_PUMPING: string = "characterPumping"
    public static COMMAND_POST: string = "commandPost"
    public static TASKS_GAME: string = "tasksGame"

    public static UPGRATE_COMMAND_POST: string = "upgrateCommandPost"
    public static UPGRATE_REPAIR_SHOP: string = "upgrateRepairShop"
    public static UPGRATE_MERGE_GOLD_MINE: string = "upgrateMergeGoldMine"
    public static UPGRATE_MERGE_TROOP_AIR: string = "upgrateMergeTroopAir"
    public static UPGRATE_MERGE_TROOP_MARINE: string = "upgrateMergeTroopMarine"
    public static UPGRATE_MERGE_TROOP_OVERLAND: string = "upgrateMergeTroopOverland"
    public static UPGRATE_MERGE_BARRACK_AIR: string = "upgrateMergeBarrackAir"
    public static UPGRATE_MERGE_BARRACK_MARINE: string = "upgrateMergeBarracMarine"
    public static UPGRATE_MERGE_BARRACK_OVERLAND: string = "upgrateMergeBarracMarine"
    public static UPGRATE_BUILD_GOLD_MINE: string = "upgrateBuildGoldMine"
    public static UPGRATE_BUILD_BARRACK_AIR: string = "upgrateBuildBarrackAir"
    public static UPGRATE_BUILD_BARRACK_MARINE: string = "upgrateBuildBarrackMarine"
    public static UPGRATE_BUILD_BARRACK_OVERLAND: string = "upgrateBuildBarrackOverland"

    public static AUTOCOMBINE: string = "autocombine"
    public static BACKPACK: string = "backpack"
    public static REPAIR_SHOP: string = "repairShop"
    public static RADAR: string = "radar"
    public static RADAR_TASK_INFO: string = "radarTaskInfo"
    public static RADAR_REWARD: string = "radarReward"
    public static BANK: string = "bank"
    public static WIRE_CUT: string = "wireCut"
    public static BOMB_DISPOSAL: string = "bombDisposal"
    public static QUESTION: string = "question"
    public static SWITCH: string = "switch"
    public static SPATIAL_MINE: string = "spatialMine"

    public static DIALOG: string = "dialog"
}